apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-db
        image: mongo
        imagePullPolicy: IfNotPresent
        volumeMounts: 
          - mountPath: /data/db
            name: mongo-vol
      volumes: 
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: host-pvc
---

kind: Service
apiVersion: v1
metadata:
  name: service-mongodb
spec:
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  selector:
    app: mongo-app